### PR TITLE
Added option to change background color

### PR DESCRIPTION
**Pull request by heavensrevenge**
Added an option to change the background color in the options page to preview the selected color, and for use both in the new tab page and the options page using localStorage.

### CODE REVIEW

**Comment by j3nda** [comment]
On 08/05/2013 02:47 PM, Eric Aguiar wrote:

> Hi, I was wondering if either of you still do stuff with the speed dial extension?  I have made a pull-request to set the background color but you may also just add an option to set a picture as-well.
> Also this Screenshot Extension sample: https://developer.chrome.com/extensions/samples.html#dcc956ee1308eb125ff32bdaad4c1d84 actually works on all tab URL's now instead of just code.google.com if you add the permission of "<all_urls>" to the manifest.json.
> 
> So I'll TRY to make it get screenshots of the opened URL's and store a small image in a url: base64 picture format in localstorage in combination of background-repeat: no-repeat;
> background-position: center top; with CSS properties.  But I am quite amateur in JS/web development so if you wanted to make it work feel free.

hi,
yes. we handle development with this extension. and some of changes take a time to test and/or must be confirmed. the main idea of this extension is "kiss" -> just keep it simple :)
please wait for comment...
thank you, j3.

**Comment by heavensrevenge** [comment]
I'm an amateur in JS but I definitely kept it simple, I'm an old time Archer(Arch linux user) so KISS is always best. I even tried to keep all your conventions the same so it blended in :)

I used Speeddial 2 for a LONG time but it seems stale & inactive now :( I even paid for pro for sync but this basically has sync built-in from using a bookmark folder so it's AMAZING mixed with the fact the extension process exits when the dial isn't open/active which helps keep the child processes to a minimal with no wasted memory.

The only thing I'll be hoping or trying to do is to get URL's register their url as a key to store a thumbnail in local storage.  The built-in tabs.captureVisibleTab API might be ok, but canvas seems to be the best suited to make that thumbnail like it shows http://stackoverflow.com/questions/14086728/genuine-jquery-javascript-jpg-image-resize even the new Chromium based Opera speed dial is based on a canvas way if you look at the source of the new Opera speed dial implementation's source.

Either way, I love this speed dial over all the others I've found so far and I'd happily help make it better not just for me but for everyone else too.

**Comment by heavensrevenge** [comment]
I also found that setting the thumbnailing service to http://immediatenet.com/t/l3?Size=1280x1024&URL=[URL] helps SO MUCH for thumbnails in the meantime, the l3 helps the page be far more correct and the bigger resolution does help them from being blurry :)

**Comment by waffleau** [comment]
Your changes have been merged and added on the Chrome Store. The only fix required was to add in a default value for the background colour setting so that the selector on the options page matched the page colour on first use. =)

**Comment by heavensrevenge** [comment]
Beautiful, I hope you also enjoy the change :)

**Comment by j3nda** [comment]
to  waffleau: nice :) and sorry, i'm late. i was on vacations...

**Comment by heavensrevenge** [comment]
:P You'll be surprised with the seemingly huge pull request I made yesterday, I updated jQuery in it and stuff which makes it smaller and faster. Hopefully in preparation to add custom icons for the dials soon. Try it out and enjoy 0 errors in the console log :P 
It seems big but it's all just housecleaning & maintenance of the code.

Hope you had a nice vacation.

**Pull request merged**
