### PR TITLE
Using Zepto instead of jQuery, Folder color, correct local folder sort, icon settings import/export textarea, a BUNCH of bug-fixes and performance improvements

### PR DESCRIPTION
**Pull request by heavensrevenge**
Changed .sort comparer to use .localeCompare() to actually sort international strings correctly, the ternary doesn't sort non-english strings right.

Has a new set Folder Icon Color feature.
Now using localStorage.getItem for 2x localStorage performance, fixed chrome.bookmarks.move API, fixed two HTML tags that were mismatched, added < tbody > tag and removed extraneous < div > in entryHtml but removed using entryHtml variable and pipe the string templates for entry & folder directly into $.append() function.
Converted to using WAY faster while (index--) loops, simplified initialize() function, using .innerHTML for folder list selection.
Removed a bunch of extra unneeded parseInt() functions since calculation/math operations do Integer conversion automatically anyway, fixed a spelling mistake, and use tabs in the manifest.json instead of spaces.

Speed dial is now down to ~68ms from ~110ms :) I'm quite glad to have render time <100ms :D
I also removed the sync/eventPage thing since I'll work on that next but well def need it for thumbnail generation :P

### CODE REVIEW

**Comment by waffleau** [comment]
Changes have been reviewed. There was an issue with the default localStorage values not being set, so parsing the icons JSON code was failing. I've fixed this now, but you'll need to pull changes from master into your repository once they've been approved.

All other changes are good except for the dragswap functionality. It makes doing mass reordering very tedious. I'd prefer to keep the original dragsort so that reordering works through insertion rather than swapping (I found it visually easier to see what was going on too). If you can revert out the dragswap changes I'll approve them and create a new release. Since it was part of the jquery-ui library hopefully it should just work with Zepto.

Keep up the good work!

**Comment by heavensrevenge** [comment]
yea its actually quite a nice drop in replacement but it THINK Zepto might not work without some crazy patch to it if you want to keep the jQuery UI I'll pull in what you push to github and get a find a drag & drop that stays visually pleasing since.. the parsing step of jQuery itself is one of the longest steps in the pipeline now :P do u want to keep the auto-sync support?? I thought from two months of silence you didn't want to use the Google sync api stuff? I basically just scrapped it from not pulling for 2 months thinking u really hated the sync ability :P 
I'll merge from your branch of what u have as soon as u push what u have here to github :)

**Comment by heavensrevenge** [comment]
I'm hoping you'll push soon because then I can work on thumbnail generation, I have 2 methods which work with an eventPage.js and I'm just getting the .addEvenetListener & removeEventListener stuff sorted out.  I'm close to thumbnails but I need to wait for what you push to your master so I can pull and sync from what you have :P

**Comment by waffleau** [comment]
I've pushed through the modifications I've made, but they include the dragswap which needs to be changed. I'll make a release once your revisions are put in.

**Comment by heavensrevenge** [comment]
are your changes in your repo now? by chance do u have Skype or a more direct way me & you can chat so that I can ask u things more directly? would be quite nice to be able to have a more direct way of communication vs comments on patches :P also did you like the synchronization? I'll put that back in if so since I THINK you're OK
 with is since in the 2.3.0 changelog notes you put "Sync across computers" :P

**Pull request merged**
