### PR TITLE
Merged with your changes, vertical centering, bug fixes, even more perf improvements, #1-9 hotkey navigation that can be used, and got the chrome.sync API all ready to go

### PR DESCRIPTION
**Pull request by heavensrevenge**
OK, have a gander and see my merge with your defaultfolder changes you made the other day, hopefully you will like the sync and enjoy how fun it is to see sync across rooms or browser sessions etc :P
Had a short fling with Zepto but switched back to jQuery + jQuery-UI.
The dial now vertically centers itself and you can use shortcut keys "s" or "o" to get to the options page and you can press numbers 1-9 to quickly go to one of the dials that are represented by the single digits 1-9, the dial needs focus to get the keypress event tho.

BTW I'll mess with thumbnail generation after you push this version to the store.

Thing is, we need an event handling page to be alive after we click through a dial, since in our case the speed dial process dies as soon as we navigate away from the dial so even timeouts or anything wont fire.  
So having sync support as step 1 to thumbnails I think is an OK 1st step right? :)

### CODE REVIEW

**Comment by heavensrevenge** [comment]
OK, I believe we're ready to go whenever you are!

**Comment by heavensrevenge** [comment]
Any progress?

**Comment by AsherGlick** [comment]
I like the new customization options but I find that if I have not set a value already the background is grey but the value shown in the menu is black. So when I save it makes the background black. It would be nice to have some defaults on those values and the ability to revert them back to the default.

Just so I can understand better: why did you replace the drag-sort functionality with a drag-swap functionality that only drags the text in the UI?

Also instead of the background page being on all the time would it be better to allow the user to refresh the thumbnail manually, via a context menu item or button in the URL bar. Or using an event page instead of a background page so that there is not a continuous process running because of the extension.

Syncing settings is also cool, it is great that the checkbox is disabled by default though as to keep the extension minimal.

**Comment by heavensrevenge** [comment]
Oh yea, i guess that  value="#hex" should be read from localStorage to show the actual value of the default or w/e is set.

I replaced the dragsort since I replaced the jQuery+jQuery-UI library with Zepto. So it's not that my intention was to change the dragsort but it's the only thing that wasn't 1-1 compatible for the attempted migration over so I found a native "HTML5" library that is Zepto compatible and tried to retro-fit it.  The only reason to try Zepto instead of jQuery is the parse+execute step of jQuery+UI was taking quite long, just swapping it out put my new tab page render time from ~120ms to ~80ms, so it's not required per-se and I/you/Eli could pretty much plug jQuery back in. 
There is one nice side-effect using Zepto has, is that all the thumbnails in cache all appear instantly instead of when using jQuery, jQuery waits for each for some reason and it delays the appearance of the thumbnails to make them appear at different future points in time that can last seconds, but reloading or opening the page with Zepto being used everything shows instantly unless the immedianet responses are lagging out.

Well the background page isn't on all the time right now from the "persistent" : false in the manifest.json file, it gets unloaded and just keeps the event listeners in the main browser instance... but that's what it takes to actually get thumbnails to be made by us instead of a service, since if we don't have something catching events after we navigate away from our new tab page, our process is destroyed and we can't process js logic, and nothing is able to catch anything and store the tab's thumbnail data in our extensions localStorage, so an absolute minimal eventPage.js is required, and sync also needs it so may as well have 1 tiny step before trying to get thumbnail generation working with that eventPage.js.  
If you look in the chrome task manager after the extension is loaded and open a ntp to kick things off, close the ntp and our eventpage/extension/background process SHOULD disappears after ~10 seconds(at least for me).

**Comment by heavensrevenge** [comment]
OK Asher fixed that color input bug, I've never noticed it since I always keep a pure black background anyway lol.

**Comment by heavensrevenge** [comment]
Any progress Matt/waffleau?

**Comment by AsherGlick** [comment]
With the update released, I must say: Nice Job! I really like the changes so far.

**Pull request merged**
